name: colorgame
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  page_transition: ^1.1.5
  flutter_bloc: ^4.0.0
  provider: any
  shared_preferences: ^0.5.7
  firebase_admob: ^0.9.3+2
  firebase_core: ^0.4.4+3
  random_color: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
flutter_icons:
  android: "launcher"
  ios: true
  image_path: "assets/logo.png"
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: assets/logo_foreground.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background.png
    - assets/us.png
    - assets/vn.png
    - assets/arrow.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/Bungee/Bungee-Regular.ttf
    - family: Bungee Inline
      fonts:
        - asset: assets/Bungee/BungeeInline-Regular.ttf
    # - family: Bungee Shade
    #   fonts:
    #     - asset: assets/Bungee/BungeeShade-Regular.ttf
    # - family: FrederickatheGreat
    #   fonts:
    #     - asset: assets/Fredericka_the_Great/FrederickatheGreat-Regular.ttf
    # - family: CabinSketch
    #   fonts:
    #     - asset: assets/Cabin_Sketch/CabinSketch-Regular.ttf
    # - family:  IconlyBroken
    #   fonts:  
    #     - asset: assets/Iconly/IconlyBroken.ttf
    # - family:  IconlyBold
    #   fonts:  
    #     - asset: assets/Iconly/IconlyBold.ttf
    # - family:  Wallpoet
    #   fonts:  
    #     - asset: assets/Wallpoet/Wallpoet-Regular.ttf
  # Wallpoet
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
